config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users
  resources :users, :only => [:show]

  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :amazing_words

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/amazing_word.rb
class AmazingWord < ActiveRecord::Base
  belongs_to :contributor, class_name: 'User'

  validates :word, presence: true
  validates :pronunciation, presence: true, format: {with: /\A[\p{hiragana}|ー| |　]+?\z/, message: 'はひらがなで入力してください'}
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]

  validates :username, presence: true, uniqueness: true

  has_many :posted_words, class_name: 'AmazingWord', foreign_key: :contributor_id, dependent: :nullify

  attr_accessor :login

  def to_param
    username
  end

  def self.find(arg)
    find_by_username(arg) || find(arg)
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { value: login }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/amazing_words_controller.rb
class AmazingWordsController < ApplicationController
  def index
    #@amazing_words = AmazingWord.find_by_sql('SELECT * FROM amazing_words ORDER BY RANDOM()').page(params[:page]).per(30)
    @amazing_words = Kaminari.paginate_array(AmazingWord.all.shuffle).page(params[:page]).per(30)

  end

  def show
    @amazing_word = AmazingWord.find(params[:id])
  end

  def new
    @amazing_word = current_user.posted_words.build
  end

  def create
    @amazing_word = current_user.posted_words.build(amazing_word_params)
    if @amazing_word.save
      redirect_to @amazing_word, notice: '作成しました'
    else
      render :new
    end
  end

  def edit
    @amazing_word = current_user.posted_words.find(params[:id])
  end

  def update
    @amazing_word = current_user.posted_words.find(params[:id])
    if @amazing_word.update(amazing_word_params)
      redirect_to @amazing_word, notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def amazing_word_params
    params.require(:amazing_word).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @amazing_words = AmazingWord.page(params[:page]).per(5)
  end
end

app/helpers/amazing_words_helper.rb
module AmazingWordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/amazing_words/_amazing_word.html.erb
<div class="amazing-word panel panel-default" style="width:275px; margin: 0 5px 10px 5px;">
  <div class="panel-body">
    <h2 style="word-break:break-all">
      <%= link_to amazing_word.word, amazing_word, title: amazing_word.pronunciation %>
    </h2>
    <p>
      <%= simple_format h(amazing_word.description) %>
    </p>

    <small class="text-muted">
      Posted by <%= link_to amazing_word.contributor.username, amazing_word.contributor %> at <%= amazing_word.created_at.to_s(:db) %>
    </small>
  </div>
</div>

app/views/amazing_words/edit.html.erb
<% provide :title, 'Edit' %>
<h1>Edit</h1>

<%= form_for(@amazing_word, class: 'form-horizontal', role: 'form') do |f| %>
  <% if @amazing_word.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @amazing_word.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :word %>
    <%= f.text_field :word, class: 'form-control', required: true, placeholder: '必須入力' %>
  </div>
  <div class="form-group">
    <%= f.label :pronunciation %>
    <%= f.text_field :pronunciation, class: 'form-control', required: true, placeholder: '必須入力' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', row: 10, required: true, placeholder: '必須入力' %>
  </div>
  <%= f.submit '編集', class: 'btn btn-default', data: { disable_with: '作成中' } %>
<% end %>

app/views/amazing_words/index.html.erb
<div id="amazing-words" style="margin: 0 auto; min-height:101%;">

  <div class="page">
    <%= render @amazing_words %>
  </div>
</div>

<%= paginate @amazing_words %>

app/views/amazing_words/new.html.erb
<% provide :title, 'Post Amazing Word' %>
<h1>New</h1>

<%= form_for(@amazing_word, class: 'form-horizontal', role: 'form') do |f| %>
  <% if @amazing_word.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @amazing_word.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :word %>
    <%= f.text_field :word, class: 'form-control', required: true, placeholder: '必須入力' %>
  </div>
  <div class="form-group">
    <%= f.label :pronunciation %>
    <%= f.text_field :pronunciation, class: 'form-control', required: true, placeholder: '必須入力' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', row: 10, required: true, placeholder: '必須入力' %>
  </div>
  <%= f.submit '作成', class: 'btn btn-default', data: { disable_with: '作成中' } %>
<% end %>

app/views/amazing_words/show.html.erb
<h1>

<ruby>
<rb><%= @amazing_word.word %></rb>
<rp>（</rp>
<rt style="text-justify: distribute;"><%= @amazing_word.pronunciation %></rt>
<rp>）</rp>
</ruby>
</h1>
<% if current_user && @amazing_word.contributor_id == current_user.id %>
  <%= link_to 'edit', edit_amazing_word_path(@amazing_word) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
<!--
        ┃
        ┣┓
      ┏┛┗┓
      ┃    ┃      ┃    ┃      ┃    ┏━━┓      ┏━━━    ┏━━┓      ┏━━━┳━━┓      ┏━━┓
    ┏┛    ┃      ┃    ┣┓    ┃  ┏┛    ┃    ━┫          ┃    ┗┓    ┃      ┃    ┃    ┏┛    ┃
    ┣━━━┻┓    ┗┓  ┃┃  ┏┛  ┣━━━┛      ┗┓      ━┫      ┃    ┃      ┃    ┃    ┣━━━┛
    ┃        ┃      ┗┳┛┗┳┛    ┃                ┗━┓    ┃      ┃    ┃      ┃    ┃    ┃
  ┏┛        ┗┓    ━┛    ┃      ┗┓    ┏━  ┃      ┃    ┃      ┃    ┃      ┃    ┃    ┗┓    ┏━
  ┃            ┃                      ┗━━┛    ┗━━━┛    ┗━━━┛            ┃            ┗━━┛

    ┏━━━┓
  ┏┛      ┗━━
  ┃
  ┃                  ┏━━┓      ┏━━┓    ┃  ┏━    ┏━━┳━  ┏━━┓
  ┃      ━━┓    ┏┛    ┃    ┏┛    ┗┓  ┣━┛    ┏┛    ┃    ┃    ┗┓
  ┃          ┃    ┣━━━┛  ━┫        ┃  ┃        ┗┓  ┏┛    ┣━━━┛
  ┗┓        ┃    ┃            ┃        ┃  ┃        ┏┻━┛      ┃
    ┗┓      ┃    ┗┓    ┏━  ┗┓    ┏┛  ┃        ┣┓          ┃      ┃
      ┗━━━┛      ┗━━┛      ┗━━┛    ┃        ┃┗━━┓    ┗━━━┛
                                                        ━┫      ┣━
                                                          ┗━━━┛
-->
  <title><%= content_for?(:title) ? "#{yield(:title)} | AwesomeGeorge" : "AwesomeGeorge"%></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Awesome George', root_path, class: 'navbar-brand' %>
      </div>

      <div class="collapse navbar-collapse" id="navbarEexample7">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Post', new_amazing_word_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path %></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', user_session_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <p class="navbar-text navbar-right">ようこそ <%= link_to current_user.username, current_user %> さん。</p>
        <% end %>
      </div>
    </div>
  </nav>
</header>

<div class="container-fluid">
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger">
      <%= fa_icon('exclamation-triangle') + ' ' + alert %>
    </div>
  <% end %>

  <main>
    <%= yield %>
  </main>
</div>

<footer>

</footer>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% provide :title, @user.username %>
<%= @user.username %>

app/views/welcome/index.html.erb
<h1>Awesome George</h1>
<ul>
  <li><%= link_to 'Amazing Words', amazing_words_path %></li>
</ul>